spring:
  datasource:
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    url: jdbc:mysql://localhost:3306/lanhu?serverTimezone=GMT
    name: realty
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.fdc.beans
  map-underscore-to-camel-case: true